
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AETTI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Proyecto
{

    public int Id { get; set; }

    public Nullable<int> NroProyecto { get; set; }

    public string TituloProyecto { get; set; }

    public Nullable<int> IdTipoProyecto { get; set; }

    public string Diagnostico { get; set; }

    public string Producto { get; set; }

    public string Resumen { get; set; }

    public string Actividades { get; set; }

    public string LinkYoutube { get; set; }

    public Nullable<int> IdPersona { get; set; }

    public string TipoProyecto { get; set; }

    public string Estado { get; set; }



    public virtual Persona Persona { get; set; }

    public virtual TipoProyecto TipoProyecto1 { get; set; }

}

}
